# Site settings
title: Weydson Lima
email: me@weydson.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.weydson.com" # the base hostname & protocol for your site
twitter_username: nosdyew
github_username:  raisen

# Build settings
markdown: kramdown

# Gems
gems: [font-awesome-sass]
timezone: America/Los_Angeles